apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@bruegner.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          webhook:
            solverName: hetzner
            groupName: acme.hetzner.com
            config:
              tokenSecretKeyRef:
                name: hetzner-credentials
                key: api-key
