apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      hostNetwork: true
      containers:
      - name: matter-server
        image: ghcr.io/matter-js/python-matter-server:stable
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: home-assistant-matter
