apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: paperless-ngx
data:
  # The UID and GID of the user used to run paperless in the container.
  # Uncomment and set this to your UID and GID on the host so that you have write access
  # USERMAP_UID: "1000"
  # USERMAP_GID: "1000"

  # This is required if you will be exposing Paperless-ngx on a public domain
  # Uncomment and adjust as needed
  PAPERLESS_URL: "https://paperless.berlin.bruegner.com"

  # Adjust this key if you plan to make paperless available publicly.
  # It should be a very long sequence of random characters.
  # PAPERLESS_SECRET_KEY: "change-me"

  # Use this variable to set a timezone for the Paperless Docker containers. Defaults to UTC.
  PAPERLESS_TIME_ZONE: "Europe/Berlin"

  # The default language to use for OCR. Set this to the language most of your documents are written in.
  # PAPERLESS_OCR_LANGUAGE: "eng"

  # Additional languages to install for text recognition, separated by a whitespace.
  # PAPERLESS_OCR_LANGUAGES: "tur ces"

  # Redis connection string
  PAPERLESS_REDIS: "redis://redis.paperless-ngx.svc.cluster.local:6379"

  # Configure the consumer directory
  PAPERLESS_CONSUMPTION_DIR: "../sync/consume"

  # Ignore files during consumption
  # I added the Nextloud client sync DB file (.sync_...db) to the list of defaults
  # For more details, see https://docs.paperless-ngx.com/configuration/#PAPERLESS_CONSUMER_IGNORE_PATTERNS
  PAPERLESS_CONSUMER_IGNORE_PATTERNS: '[".DS_Store", ".DS_STORE", "._*", ".stfolder/*", ".stversions/*", ".localized/*", "desktop.ini", "@eaDir/*", "Thumbs.db", ".sync_*"]'

  # Configure the filename format for exported documents
  PAPERLESS_FILENAME_FORMAT: "{{ document_type }}/{{ correspondent }}/{{ created }}_{{ title }}"

  # Delete detected duplicates
  PAPERLESS_CONSUMER_DELETE_DUPLICATES: "true"

  # Enable recursive consumption of documents in the consume directory
  PAPERLESS_CONSUMER_RECURSIVE: "true"

  # Enable polling interval in seconds for the consume directory
  PAPERLESS_CONSUMER_POLLING: "15" # seconds
