apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pi-hole
  namespace: pi-hole
  labels:
    app: pi-hole
spec:
  ingressClassName: nginx
  rules:
  - host: pihole.berlin.bruegner.com
    http:
      paths:
      - backend:
          service:
            name: pi-hole
            port:
              number: 80
        path: /
        pathType: Prefix
